spring:
  application:
    name: product-api
  datasource:
    url: jdbc:h2:file:./database/database;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  threads:
    virtual:
      enabled: true

application:
  version: @project.version@