spring:
  application:
    name: product-api
  datasource:
    url: jdbc:h2:file:./database/database;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

application:
  version: 0.0.1

tracing:
  url: http://localhost:4318/v1/traces

otel:
  logs:
    exporter: none
  metrics:
    exporter: none

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Enables 100% sampling of traces

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]'